const crypto = require("crypto");

function sanitizeDocumentValue(
  value
) {
  return String(value || "")
    .replace(
      /[\u0000-\u001f\u007f]/g,
      " "
    )
    .trim();
}

function buildPolicyAcknowledgementDocument({
  acknowledgementId,
  user,
  policyType,
  policyTitle,
  policyVersion,
  acknowledgementText,
  acknowledgedAt
}) {
  const lines = [
    "MEGA FINANCIAL",
    "POLICY ACKNOWLEDGEMENT RECORD",
    "",
    "This document is a system-generated record of a client policy acknowledgement.",
    "",
    `Acknowledgement ID: ${sanitizeDocumentValue(
      acknowledgementId
    )}`,
    `Client ID: ${sanitizeDocumentValue(
      user.id
    )}`,
    `Client Name: ${sanitizeDocumentValue(
      user.fullName
    )}`,
    `Client Email: ${sanitizeDocumentValue(
      user.email
    )}`,
    `Policy Type: ${sanitizeDocumentValue(
      policyType
    )}`,
    `Policy Title: ${sanitizeDocumentValue(
      policyTitle
    )}`,
    `Policy Version: ${sanitizeDocumentValue(
      policyVersion
    )}`,
    `Acknowledged At: ${acknowledgedAt.toISOString()}`,
    "",
    "ACKNOWLEDGEMENT",
    sanitizeDocumentValue(
      acknowledgementText
    ),
    "",
    "This record was generated by the Mega Financial Web App following an authenticated acknowledgement.",
    ""
  ];

  return Buffer.from(
    lines.join("\n"),
    "utf8"
  );
}

function hashPolicyAcknowledgementDocument(
  buffer
) {
  if (!Buffer.isBuffer(buffer)) {
    throw new Error(
      "Acknowledgement document must be a Buffer."
    );
  }

  return crypto
    .createHash("sha256")
    .update(buffer)
    .digest("hex");
}

module.exports = {
  buildPolicyAcknowledgementDocument,
  hashPolicyAcknowledgementDocument
};
